@GradGo_HostAddress = https://localhost:7086

GET {{GradGo_HostAddress}}/jobs/
Accept: application/json

###

GET {{GradGo_HostAddress}}/jobs/search?skills=C%23&skills=.Net
Accept: application/json

###

Get {{GradGo_HostAddress}}/skills/
Accept: application/json

###
