@GradGo_HostAddress = https://localhost:7086

###

GET {{GradGo_HostAddress}}/skills
Accept: application/json

###

GET {{GradGo_HostAddress}}/skills/3
Accept: application/json

###

POST {{GradGo_HostAddress}}/skills
Content-Type: application/json

{
    "Title": "ASP.Net"
}

###

PUT {{GradGo_HostAddress}}/skills/3
Content-Type: application/json

{
    "Id": 3,
    "Title": "ASP.NET"
}

###
