@GradGo_HostAddress = https://localhost:7086

###

GET {{GradGo_HostAddress}}/employers
Accept: application/json

###

GET {{GradGo_HostAddress}}/employers/01982e42-14e2-721f-b66a-7ae509e52905
Accept: application/json

###

POST {{GradGo_HostAddress}}/employers
Content-Type: application/json

{
    "Name": "Deliveroo",
    "City": "Manchester",
    "CountryId": 2,
    "StaffCount": 1
}

###

PUT {{GradGo_HostAddress}}/employers/01982e42-14e2-721f-b66a-7ae509e52905
Content-Type: application/json

{
    "StaffCount": 3
}

###

DELETE {{GradGo_HostAddress}}/employers/01982e42-14e2-721f-b66a-7ae509e52905

###