@GradGo_HostAddress = https://localhost:7086

###

GET {{GradGo_HostAddress}}/jobs
Accept: application/json

###

GET {{GradGo_HostAddress}}/jobs/3
Accept: application/json

###

POST {{GradGo_HostAddress}}/jobs
Content-Type: application/json

{
    "EmployerId": "019828f2-9b70-76f0-877c-7d05021d457b",
    "CountryId": 1,
    "Description": "your valid description here (min 100 chars)sdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsasdasdasdasdasdasdasdasdadsad",
    "Type": 1,
    "Salary": 100,
    "City": "Cardiff",
    "RequiredDegree": "Bachelors",
    "Skills": [ 11 ]
}


###

PUT {{GradGo_HostAddress}}/jobs/1
Content-Type: application/json

{
    "EmployerId": 1,
    "Description": "lsnflknsal;dfnnasldfnlsnadlfnlskadnflasklfjlasdlfk;jaslk;dfjlsjadflkjaslfjlaskjdflk;jsadlkfjlsajdlf;jaslkdjflkjsadljfljsadfljlasd;jf",
    "Type": "Remote",
    "Salary": 1000,
    "City": "Swansea",
    "Country": "UK",
    "RequiredDegree": "Bachelors",
    "ApplicantsNo": 0,
    "Skills": [
        3,
        11
    ]
}