@GradGo_HostAddress = https://localhost:7086

###

GET {{GradGo_HostAddress}}/skills
Accept: application/json

###

GET {{GradGo_HostAddress}}/skills/3
Accept: application/json

###

POST {{GradGo_HostAddress}}/skills
Content-Type: application/json

{
    "Title": "C#"
}

###

PUT {{GradGo_HostAddress}}/skills/11
Content-Type: application/json

{
    "Title": "C++"
}

###

DELETE {{GradGo_HostAddress}}/skills/5

###