@GradGo_HostAddress = https://localhost:7086

###

GET {{GradGo_HostAddress}}/employers
Accept: application/json

###

GET {{GradGo_HostAddress}}/employers/019833f8-a7ca-7302-bfc2-af0e2fa5ba15
Accept: application/json

###

POST {{GradGo_HostAddress}}/employers
Content-Type: application/json

{
    "Name": "Microsoft",
    "Email": "microsoft@gmail.com",
    "City": "London",
    "CountryId": 1,
    "StaffCount": "MoreThan500"
}

###

PUT {{GradGo_HostAddress}}/employers/019833f8-a7ca-7302-bfc2-af0e2fa5ba15
Content-Type: application/json

{
    "StaffCount": "MoreThan500"
}

###

DELETE {{GradGo_HostAddress}}/employers/019833f8-a7ca-7302-bfc2-af0e2fa5ba15

###